---
# =====================================================
# AutoCloud Enterprise
# Master Ansible Playbook
# =====================================================

- name: Configure base infrastructure
  hosts: all
  become: true
  gather_facts: true

  roles:
    # - common
    - linux_admin

- name: Configure Docker infrastructure
  hosts: docker_hosts
  become: true
  gather_facts: true

  roles:
    - docker